version: "2"
services:
  ngrok:
    image: wernight/ngrok
    ports:
    - "4040:4040"
    command:
    - /bin/sh
    - -c
    - |
      ngrok http -region=au -subdomain=hermes-staging mock-app:4390
    volumes:
    - .:/home/ngrok/.ngrok2/
    depends_on:
    - mock-app
  mock-app:
    build: .
    ports:
    - "4390:4390"